### ISSUE TITLE
Upgrade QA Wayback to PyWB 2.6.2

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-services#51]
Following https://github.com/ukwa/ukwa-pywb/issues/71, upgrade W3ACT's Wayback and verify with @crarugal that https://github.com/ukwa/ukwa-pywb/issues/70 is resolved.

**Comment by ikreymer** [comment]
Should now be 2.6.2 due to regression in 2.6.1 (now fixed).

**Comment by anjackson** [comment]
This is now released on DEV, as per https://github.com/ukwa/ukwa-pywb/issues/70

**Comment by anjackson** [comment]
This is done but awaiting rollout.
