### ISSUE TITLE
Deduplicate tests?

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-services#66]
The repeated tests in browse.robot might lend themselves to being simplified/deduplicated using a custom keyword.

**Comment by anjackson** [comment]
Yes, that sounds like a good idea, although I can't quite tell whether this would make it harder to understand?

One simplification would be to only do a single check after log out:

https://github.com/ukwa/ukwa-services/blob/947cf79bf0f19cd81dd1987104fa76e6713ed74d/ingest/ingest_tests/tests/browse.robot#L58-L60

Looking at it now, going back to them all yet again seems like overkill.

**Comment by anjackson** [comment]
I simplified the tests as per my comment above: https://github.com/ukwa/docker-robot-framework/commit/1664969f964241a4e5c2a9b367c5279bdb6e9eae

I'm happy with that for now, but it's up to you if you want to deduplicate further @ldbiz
