### ISSUE TITLE
Launching robot clarification

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-services#67]
The procedure for launching robot tests might need some clarification or refactoring, especially wrt to environment vars. 

eg. The .env files need "export"'s removing before normal docker-compose usage, but have been retained as they are used in that format elsewhere. 

The website scripts (as example) are here:
https://github.com/ukwa/ukwa-services/blob/master/access/website/deploy-access-website.sh

**Comment by anjackson** [comment]
I think this has been resolved by https://github.com/ukwa/docker-robot-framework#how-to-build-and-run-these-tests  - if you agree then this can be closed, @ldbiz
