### ISSUE TITLE
Possible ePub performance optimisations

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-services#93]
During testing for https://github.com/ukwa/ukwa-pywb/issues/92, some performance issues arose with ePubs, particularly large ones (the largest being 2.5GB!).  It seems this is a known issue, and as per [this documentation from the Readium project](https://docs.google.com/document/d/1bwv89vSmLbUs4tHOwiqyeV546k5CG3RCJ1S6_-4wvvc/edit#), is is recommended to serve ePubs in an unpacked form.

Unpacking whole files would be slow when pulling large epubs from the library store, so we could use e.g. [remotezip](https://github.com/gtsystem/python-remotezip) to create an API that streams our the contents of the ZIPs.

This seems to be called a 'streamer' in Readium parlance, so there are possible implementations there that could be used instead, e.g. https://github.com/readium/r2-streamer-js and see [remote-epub](https://github.com/readium/r2-streamer-js/blob/develop/docs/remote-epub.md) and the [corresponding API](https://github.com/readium/r2-streamer-js/blob/develop/docs/http.md#get-url-and-urlencoded_url)

Alternatively, and with the advantage of perhaps making printing easier, a server-side process could be used to convert the ePub to PDF, like https://manual.calibre-ebook.com/generated/en/ebook-convert.html

**Comment by anjackson** [comment]
Put together a quick prototype ePub streamer here: https://github.com/ukwa/epub-streamer

An alternative that might make more sense would be to extract the viewers themselves from PyWB, and run them as one or more standalone services.

**Comment by mtgch3** [comment]
Quick note on option 3 - 
John G and I put using calibre to always convert epub to pdf forward as a solution to a few things a couple of years ago. At the time, that was turned down as it was felt important that patrons viewed the content in it's actual format. 
It's still the case that it would allow us to solve many rendering and print issues in advance but would probably need the same discussion as last time. Could being it up in issues chat this morning and see.

**Comment by anjackson** [comment]
Thanks @mtgch3  - As I said in the meeting, I lean towards letting our readers choose what version they would like (see e.g. this old blog on [user-driven digital preservation](https://blogs.bl.uk/webarchive/2014/08/user-driven-digital-preservation-with-interject.html)). The downside is it means we have to support more software in the access stack, so I'll be curious to see where we end up.

**Comment by anjackson** [comment]
Current version includes experimental ePub unpacker/streamer. Makes is possible to use very large ePubs (although it's still a bit sluggish because the index and pages are still pretty large),  Will review during deployment.
